# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

absolute_residual_scores_cpp <- function(y_pred, y_true) {
    .Call(`_Algorithmique_absolute_residual_scores_cpp`, y_pred, y_true)
}

simultaneous_coverage_cpp <- function(y_true, y_lower, y_upper) {
    .Call(`_Algorithmique_simultaneous_coverage_cpp`, y_true, y_lower, y_upper)
}

get_sorted_scores_cpp <- function(Scores) {
    .Call(`_Algorithmique_get_sorted_scores_cpp`, Scores)
}

get_Beta_quantiles_cpp <- function(sorted_Scores, Beta) {
    .Call(`_Algorithmique_get_Beta_quantiles_cpp`, sorted_Scores, Beta)
}

get_prediction_bounds_cpp <- function(quantile, y_pred) {
    .Call(`_Algorithmique_get_prediction_bounds_cpp`, quantile, y_pred)
}

column_wise_rank_cpp <- function(mat) {
    .Call(`_Algorithmique_column_wise_rank_cpp`, mat)
}

R_max_vector_cpp <- function(rank_matrix) {
    .Call(`_Algorithmique_R_max_vector_cpp`, rank_matrix)
}

get_r_max_scalar_cpp <- function(R_max, alpha) {
    .Call(`_Algorithmique_get_r_max_scalar_cpp`, R_max, alpha)
}

max_rank_quantiles_cpp <- function(r_max, sorted_score_matrix) {
    .Call(`_Algorithmique_max_rank_quantiles_cpp`, r_max, sorted_score_matrix)
}

dichotomie_wrapper_cpp <- function(target, xmin, xmax, n_iter, R_max) {
    .Call(`_Algorithmique_dichotomie_wrapper_cpp`, target, xmin, xmax, n_iter, R_max)
}

simultaneous_coverage_bis_wrapper_cpp <- function(R_max, Beta) {
    .Call(`_Algorithmique_simultaneous_coverage_bis_wrapper_cpp`, R_max, Beta)
}

fit_cpp <- function(y_pred_calib, Y_calibration, uncertainty_method, Global_alpha) {
    .Call(`_Algorithmique_fit_cpp`, y_pred_calib, Y_calibration, uncertainty_method, Global_alpha)
}

predict_cpp <- function(y_pred_test, quantiles) {
    .Call(`_Algorithmique_predict_cpp`, y_pred_test, quantiles)
}

